name: Publish gd-ui-vite To NPM

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed
  
jobs:
  validate:
    # 新增startsWith，用于修复非publish-gd-ui分支的pull_request合并到main分支，也会触发该工作流进行发布npm包
    if: github.head_ref == "publish-gd-ui"
    runs-on: ubuntu-latest
    steps:
      - name: Output some message
        run: echo "validate pass......."
  publish:
    needs: validate
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: npm
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Module
        run: pnpm install
      - name: Build
        run: cd packages/gd-ui-vite && pnpm run build
      - name: copy dep to package
        run: cd packages/gd-ui-vite && cp package.json dist/package.json && cp README.md dist/README.md
      - run: npm publish packages/gd-ui-vite/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}