name: Publish GsUI To NPM

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed
  
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: npm
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Module
        run: pnpm install
      - name: Build
        run: cd packages/gs-ui && pnpm run build
      - name: copy dep to package
        run: cd packages/gs-ui && cp package.json dist/package.json && cp README.md dist/README.md
      - run: npm publish packages/gs-ui/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}